site_name: MC Create Aeronautics
site_description: NeoForge модпак Minecraft и серверный образ, сопровождаемые через Git.
site_url: https://alexcawl.github.io/mc-create-aeronautics-modpack/
repo_url: https://github.com/AlexCawl/mc-create-aeronautics-modpack

nav:
  - Главная: index.md
  - Моды: mods.md
  - Конфиги: modpack.md

theme:
  name: mkdocs

extra_css:
  - assets/stylesheets/extra.css

strict: true
