site_name: MC Create Aeronautics
site_description: Git-first NeoForge Minecraft modpack and server image.
site_url: https://alexcawl.github.io/mc-create-aeronautics-modpack/
repo_url: https://github.com/AlexCawl/mc-create-aeronautics-modpack

nav:
  - Home: index.md
  - Modpack: modpack.md
  - Mods: mods.md

theme:
  name: mkdocs

extra_css:
  - assets/stylesheets/extra.css

strict: true
