name = "MC Create Aeronautics"
author = "MC Create Aeronautics"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18e9c5ff778b8c4dd03782e6432e8e25c2db85ea7230940bfdf6aa8b275ba028"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
