name = "MC Create Aeronautics"
author = "MC Create Aeronautics"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d52bf105e2c126df3a6d5e8d2f472a2a51f4aeceec127e7911e0343754b6aaed"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
