name = "MC Create Aeronautics"
author = "MC Create Aeronautics"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3668af8347d263ccb105e0e625e02229924ac5e6cc88956432a997eecc3b74e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
